### ISSUE TITLE
refactor use of assertions in enum string

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/team5#103]

**Comment by yossigil** [comment]
data members can be public, but only if immutable:

public double degrees;
  public double radians;	  public double radians;

**Comment by shaked-sapir** [comment]
@yossigil  Hi, what data members you are talking about? in string.java . there are only two static data members, and the string.test does not include any Junit Asserts, as of this issue's goal

**Comment by shaked-sapir** [comment]
@yossigil @dormaayan  Hi, could one of you please answer my question in the above comment? I want to close it if I possible

**Comment by yossigil** [comment]
oops this was for class angle #96

**Comment by shaked-sapir** [comment]
got it, then I am closing the issue
