### ISSUE TITLE
search & read material about vocal aids: Cortana

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/team5#105]
search & read material about Cortana, connected to issue #97

**Comment by yossigil** [comment]
your task is to create a short wike that summarizes prospects of using technology for project

**Comment by shalev-kuba** [comment]
@yossigil from our researches, cortana's skill developing is possible only with .NET and javascript, which makes it irrelevent to our project.
i am closing this issue.
we will move forward with Alexa and Google home+assistant.
