### ISSUE TITLE
search & read material about vocal aids: Alexa

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/team5#106]
search & read material about Alexa, connected to issue #97

**Comment by yossigil** [comment]
your task is to create a short wike that summarizes prospects of using technology for project

**Comment by shalev-kuba** [comment]
we sumed up all information we learned at: [alexa wiki page](https://github.com/TechnionYP5779/team5/wiki/Alexa-sprint1-meeting-%231-:-04.12.18)

**Comment by igorbash** [comment]
I am closing this as it was moved to the FItnesspeaker's repo
