### ISSUE TITLE
Create meeting summary page in our Wiki

### ISSUE THREAD

**Issue by shalev-kuba** [TechnionYP5779/team5#113]
also, need to summary our first meeting.
@shaked-sapir can you please upload the things you wrote when we talked about our project idea with Yossi?

**Comment by yossigil** [comment]
closing commit is unrelated, please include a link to wiki before closing

**Comment by shaked-sapir** [comment]
https://github.com/TechnionYP5779/team5/wiki/team5-meeting-%233:-07.11.18
