### ISSUE TITLE
Check again that you do not use junit Assert, but only class azzert

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team5#121]
_From @yossigil on November 14, 2018 9:14_

You can do this manually, or write a script. it is up to you. 

_Copied from original issue: TechnionYP5779/team6#79_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#76

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#61

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#79

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#106

**Comment by LiorBenYamin** [comment]
<img width="1083" alt="screen shot 2018-11-14 at 11 31 27" src="https://user-images.githubusercontent.com/31311573/48473532-4f6db000-e801-11e8-8efa-924eb4e0c9bf.png">

**Comment by yossigil** [comment]
Maybe use Ctrl-Shift-G

**Comment by shalev-kuba** [comment]
![image](https://user-images.githubusercontent.com/34859568/48785038-94578200-ecec-11e8-9d3d-190362884e68.png)

**Comment by LiorBenYamin** [comment]
@NirChachmovitz  please check me here as part of #124

**Comment by NirChachmovitz** [comment]
Hi Lior,
I searched the project for uses of the class 'assert',
and only found references such as "assert x" for x that is a boolean value, as requested.
