### ISSUE TITLE
Document a push procedure in a wiki page

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team5#122]
_From @yossigil on November 14, 2018 9:11_

Should include formatting, cleanup, tests, spartanization etc.

_Copied from original issue: TechnionYP5779/team6#78_

**Comment by igorbash** [comment]
@dormaayan  what do you mean?

**Comment by yossigil** [comment]
You are supposed to create wiki page in your project, which documents what should be done before you comit.

Also, @igorabsh, make sure that all team members understand the concept of wiki page in the project

**Comment by igorbash** [comment]
done:
https://github.com/TechnionYP5779/team5/wiki/Push-Procedure

**Comment by yossigil** [comment]
add instructions to format the code before push

**Comment by yossigil** [comment]
@igorbash : please do not close issues without providing evidence for these being closed.
also, please follow directions regarding labels.

@LiorBenYamin: can you please work out with Igor on this point.

**Comment by igorbash** [comment]
https://github.com/TechnionYP5779/team5/wiki/Push-Procedure

@LiorBenYamin please check its ok

**Comment by yossigil** [comment]
@LiorBenYamin please check igor'w work and close

**Comment by LiorBenYamin** [comment]
![image](https://user-images.githubusercontent.com/31311573/48762860-a1587f00-ecb4-11e8-88a4-9df2788b88a9.png)
seems good to me
