### ISSUE TITLE
Reopen all non-trivial issues, and make sure that someone else closes them

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team5#124]
_From @yossigil on November 14, 2018 9:2_

in particular, if you closed an non-trivial issue, reopen it, and ask someone else in your team verifies that the issue can be closed.

_Copied from original issue: TechnionYP5779/team6#76_

**Comment by yossigil** [comment]
Do not close this issue, without demonstrating that you indeed fixed some closed issues.

**Comment by yossigil** [comment]
Please add a commit number for all issues that were closed without a commit number.
This is an exercise in searching git history

**Comment by shalev-kuba** [comment]
reopened mine #66, #79, #120 and #155 
@shaked-sapir can you please review?
thank in advance

**Comment by shaked-sapir** [comment]
re-opened non-trivial issues of mine: #139 , #118 , #83 , #63 
@shalev-kuba please close them

**Comment by shalev-kuba** [comment]
> re-opened non-trivial issues of mine: #139 , #118 , #83 , #63
> @shalev-kuba please close them

hey @shaked-sapir , i reviewed these issues, nice job !

**Comment by igorbash** [comment]
re-opened non-trivial issues of mine: #28, #29, #65, #82, #133, #154
@orfeld415  please close them

**Comment by LiorBenYamin** [comment]
re-opened non-trivial issues of mine: #96, #121, #92.
@NirChachmovitz please close them

**Comment by NirChachmovitz** [comment]
reopened #123, #94 and #165.
@LiorBenYamin please check them out!

**Comment by LiorBenYamin** [comment]
> reopened #123, #94 and #165.
> @LiorBenYamin please check them out!

I checked all of them, Looks good !

**Comment by orfeld415** [comment]
reopened #80 #62 #144 
@igorbash please close them

**Comment by igorbash** [comment]
Checked and Closed @orfeld45 issues
