### ISSUE TITLE
Test runs should be with assertions enabled

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team5#126]
_From @yossigil on November 14, 2018 9:21_

Play with eclipse, it is better to write
`assert x`
then
`azzert.isTrue(x)`

but when you run tests the jvm should have assertions enabled

_Copied from original issue: TechnionYP5779/team6#82_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#81

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#66

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#84

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#111

**Comment by yossigil** [comment]
You should use a jvm flag. Can you please show where this flag is set? use screen dump if necessary

**Comment by LiorBenYamin** [comment]
![image](https://user-images.githubusercontent.com/31311573/48808573-f2568a80-ed29-11e8-828a-4adf1dc1a8fa.png)

In Eclipse toolbar->Run->Run Configurations->JUnit->team5->Arguments. check that there is -ea flag in VM arguments and if there isn't, add it.
@shalev-kuba @NirChachmovitz  @shaked-sapir  @orfeld415  @igorbash

**Comment by shalev-kuba** [comment]
![image](https://user-images.githubusercontent.com/34859568/48810033-c3431780-ed2f-11e8-8a63-53e9e023dc85.png)

**Comment by igorbash** [comment]
![untitled](https://user-images.githubusercontent.com/22839039/48820139-38c4dd00-ed5c-11e8-98c6-e2636cfa45b1.png)

**Comment by shaked-sapir** [comment]
![image](https://user-images.githubusercontent.com/41997832/48820998-1c2aa400-ed60-11e8-80ab-b1b219bdf221.png)

**Comment by NirChachmovitz** [comment]
![image](https://user-images.githubusercontent.com/44426796/48824230-58640180-ed6c-11e8-98b8-15dab33f8d40.png)

**Comment by orfeld415** [comment]
![pic](https://user-images.githubusercontent.com/44426542/48824346-ada01300-ed6c-11e8-96fd-fd4f89adb59a.png)
