### ISSUE TITLE
Integrate github issues with eclipse

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team5#127]
_From @yossigil on November 14, 2018 9:24_

for this, you need a proper mylyn connector. Best done by one team member figruing this out, and then
letting him instruct other members.

in short, github issues should be shown in the eclipse task list view.

![image](https://user-images.githubusercontent.com/12775400/48472870-e174b900-e7ff-11e8-8357-cf6c77bd12c5.png)

this is what the end results looks like in my machine. I can even see this issue on my eclipse:

![image](https://user-images.githubusercontent.com/12775400/48473379-03bb0680-e801-11e8-99b9-64c5d470c03a.png)

_Copied from original issue: TechnionYP5779/team6#83_

**Comment by dormaayan** [comment]
_From @yossigil on November 14, 2018 9:26_

be sure to enter the github password to and save it in eclipse, otherwise, you will get errors in synching.

here is where you add the password

![image](https://user-images.githubusercontent.com/12775400/48473150-8c857280-e800-11e8-8b18-152753de853c.png)

**Comment by dormaayan** [comment]
_From @yossigil on November 14, 2018 9:30_

![image](https://user-images.githubusercontent.com/12775400/48473035-3dd7d880-e800-11e8-8753-e906d36a448d.png)

this is where you add repos.

**Comment by dormaayan** [comment]
_From @yossigil on November 14, 2018 9:37_

hint, do an internet search

**Comment by yossigil** [comment]
how is it going?

**Comment by shalev-kuba** [comment]
@shaked-sapir @orfeld415 @LiorBenYamin @igorbash @NirChachmovitz 
please follow this wiki page for integrate github issues to your eclipse:
[integrate wiki page](https://github.com/TechnionYP5779/team5/wiki/Integrate-github-issues-with-eclipse)
add an image like this to prove the github was integrated to your eclipse:
![image](https://user-images.githubusercontent.com/34859568/48703852-b4f4de80-ebfd-11e8-9476-16d3dd149500.png)
i am asking the last of you who uploads his image to close this issue

**Comment by shaked-sapir** [comment]
all is fine with me
![image](https://user-images.githubusercontent.com/41997832/48709563-7f0c2600-ec0e-11e8-9d9b-20e8da79297f.png)

**Comment by igorbash** [comment]
done

![git issues](https://user-images.githubusercontent.com/22839039/48718478-26e01e80-ec24-11e8-9c50-e00af97ae105.jpg)

**Comment by orfeld415** [comment]
![issue 127](https://user-images.githubusercontent.com/44426542/48728810-b1ce1280-ec3e-11e8-9f0a-31ec88eb9175.png)

**Comment by shalev-kuba** [comment]
@LiorBenYamin @NirChachmovitz  ??

**Comment by LiorBenYamin** [comment]
![image](https://user-images.githubusercontent.com/31311573/48807855-870bb900-ed27-11e8-8995-f9d520a22fa1.png)

**Comment by NirChachmovitz** [comment]
![image](https://user-images.githubusercontent.com/44426796/48823504-bba06480-ed69-11e8-8cf0-ef1eb0e052b8.png)
