### ISSUE TITLE
connect your project to SonarQube

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team5#128]
for now, just connect. later we shall decide which rules to use.

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#83

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#68

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#86

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#113

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team6#85

**Comment by NirChachmovitz** [comment]
connected the project 'team5' to sonarcube.
https://sonarcloud.io/organizations/team5/projects

**Comment by NirChachmovitz** [comment]
@yossigil We have some bugs in our pregiven code, should we fix them?
![image](https://user-images.githubusercontent.com/44426796/48706481-17051200-ec05-11e8-9f7b-2319c20b5d90.png)

**Comment by shalev-kuba** [comment]
i included a link to sonarqube and lgtm in our readme.md
