### ISSUE TITLE
  @SuppressWarnings("boxing")

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team5#129]
_From @yossigil on November 14, 2018 11:9_

This should never occur in the code, perhaps with the exception of class "box"
Use class box, and/or box.it() instead.

Only close this issue with a screen dump showing search for   @SuppressWarnings("boxing")

_Copied from original issue: TechnionYP5779/team6#87_

**Comment by yossigil** [comment]
this one seems to be OK, but @shaked-sapir, please check and close it when you are convinced it is

**Comment by shaked-sapir** [comment]
@yossigil  re-checked , that is indeed OK.
