### ISSUE TITLE
Create a cleanup profile for eclipse, and save it with your projecrt

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team5#131]
_From @yossigil on November 14, 2018 11:21_

Connect this profile with the wiki you created for a commit procedure

![image](https://user-images.githubusercontent.com/12775400/48479501-315b7c00-e810-11e8-997e-c2a63792c609.png)

_Copied from original issue: TechnionYP5779/team6#88_

**Comment by shalev-kuba** [comment]
![image](https://user-images.githubusercontent.com/34859568/48704947-8cbaaf00-ec00-11e8-92d1-5b5195b52ce6.png)

**Comment by shalev-kuba** [comment]
see the following wiki page:
[how to import the new cleanup profile](https://github.com/TechnionYP5779/team5/wiki/import-our-cleanup-profile)
