### ISSUE TITLE
eliminate all   @SuppressWarnings

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team5#132]
_From @anny234 on November 14, 2018 10:28_

from  all code that you wrote. do not add @SuppressWarnings unless there is no other choice

_Copied from original issue: TechnionYP5779/team3#89_

**Comment by shalev-kuba** [comment]
@shaked-sapir i am closing this issue after i verified it and it seemed good to me, can you please recheck me and reopen this issue if you see somthing wrong?
