### ISSUE TITLE
Convert azzert.that(X, is(true)) to assert x

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team5#133]
_From @yossigil on November 14, 2018 20:39_

Similalry, convert azzert.that(X, is(false)) to assert !x
Similalry, convert azzert.thattrue, is(Boolean.FALSE)) to assert !x,
etc.

_Copied from original issue: TechnionYP5779/team6#90_

**Comment by yossigil** [comment]
`    @NotNull public Asserter andNay(final @NotNull String reason, final boolean claim) {
      azzert.that(reason, claim, is(false));
      return this;
    }`

**Comment by yossigil** [comment]
labels and milestone?

**Comment by igorbash** [comment]
azzert.that(reason, claim, is(false)); return this;
@yossigil how can I refactor this line to use assert?

**Comment by yossigil** [comment]
read the manual of Java assert command. it is explained there.

(take note that I cannot read all issues immediately, so don't always wait for my answers.)

**Comment by igorbash** [comment]
reopened as part of issue #124, @orfeld415  asking you to close
