### ISSUE TITLE
instead of assertEquals(a, b)  use azzert.that(a, is(b)), same for assertNotEquals

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team5#149]
e.g., in isTest.java, __Test.java, pruneTest

**Comment by shalev-kuba** [comment]
![image](https://user-images.githubusercontent.com/34859568/48723318-f6ea4880-ec2e-11e8-98b8-b186db4c4bdf.png)

and

![image](https://user-images.githubusercontent.com/34859568/48723332-01a4dd80-ec2f-11e8-8bbf-0b7a91b81361.png)

these functions are used only by class azzert
