### ISSUE TITLE
factor out @SuppressWarnings("unused"), if applies to many methods in class, e.g., in forget

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team5#161]

**Comment by shalev-kuba** [comment]
as you can see, one @SuppressWarnings("unused") per class
![image](https://user-images.githubusercontent.com/34859568/48789773-78f17480-ecf6-11e8-9df5-1cc9c38ce1e2.png)

![image](https://user-images.githubusercontent.com/34859568/48789790-83137300-ecf6-11e8-8c59-8bb19fe07502.png)

![image](https://user-images.githubusercontent.com/34859568/48789815-8c9cdb00-ecf6-11e8-9e27-891a4e257d14.png)

@shaked-sapir i am closing this issue, please verify me, and reopen if you see somthing wrong.

**Comment by shaked-sapir** [comment]
verified by me, seems ok
