### ISSUE TITLE
Polish: convert azzert.that(the.max(1, 3, 2), azzert.is(3)) to  azzert.that(the.max(1, 3, 2), is(3)) [hint: search for ", azzert.is("

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team5#164]

**Comment by yossigil** [comment]
![image](https://user-images.githubusercontent.com/12775400/49217456-43274c80-f3d6-11e8-8cb3-e48e69262031.png)

**Comment by igorbash** [comment]
![image](https://user-images.githubusercontent.com/22839039/49225760-9062e880-f3ed-11e8-9c17-c8ff2d6d5419.png)
