### ISSUE TITLE
Make sure all tests conform to the recommended maven structure

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team5#17]

**Comment by LiorBenYamin** [comment]
👍

**Comment by shaked-sapir** [comment]
👍

**Comment by shalev-kuba** [comment]
👍

**Comment by yossigil** [comment]
Tests should be in the test folder, as per maven recommendation

**Comment by shalev-kuba** [comment]
Do you mean we should move the existing tests to test folder or we only should put our new test cases in test folder?

**Comment by yossigil** [comment]
no, it is not done.
![image](https://user-images.githubusercontent.com/12775400/48222916-790c7e80-e39e-11e8-83d0-ff482864cd78.png)


please include a screen dump before you close again

**Comment by LiorBenYamin** [comment]
<img width="354" alt="screen shot 2018-11-12 at 19 33 08" src="https://user-images.githubusercontent.com/31311573/48365054-710c5180-e6b2-11e8-8ffd-a020cc5212fc.png">
