### ISSUE TITLE
Understanding and analyzing the JavaFX GUI Database

### ISSUE THREAD

**Issue by NirChachmovitz** [TechnionYP5779/team5#190]
Great resources to read:

- Learn Java GUI Programming in JavaFX : http://zetcode.com/gui/javafx/
- Getting started with JavaFX : https://www.swtestacademy.com/getting-started-with-javafx/
- Database Operations in JavaFX : https://www.swtestacademy.com/database-operations-javafx/

**Comment by LiorBenYamin** [comment]
As part of #186 and #181

**Comment by igorbash** [comment]
Decided to use web technology
