### ISSUE TITLE
Look for GUI Technology for the parking project and write about it in the wiki

### ISSUE THREAD

**Issue by igorbash** [TechnionYP5779/team5#191]
https://github.com/TechnionYP5779/team5/wiki/GUI-for-the-Parking-Project

**Comment by yossigil** [comment]
A rationale selection process is that there are two or three competing offers, with advocates for each. Then have the selection done in a team meeting.

I am not sure I understand this issue though. Have you decided on JavaFX? Doesn't seem like it.

**Comment by LiorBenYamin** [comment]
Wrote about Qt Jambi in the Wiki Page. In the Wiki page there are links to how integrate it with eclipse and tutorials...

**Comment by igorbash** [comment]
Wrote about JavaFX in the wiki page.

**Comment by orfeld415** [comment]
Wrote about Swing in the wiki page.

**Comment by igorbash** [comment]
Decided to use web technology
