### ISSUE TITLE
Build a database for User-info

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/team5#198]
Build  a database holding the user's information.
For the prototype, this will include the following:

**personal info:**
user_gender, user_age, user_weight

**personal "food" info:** 
daily_calories,  daily_goal_of_calories,
daily_amount_of_water, goal_for_daily_amount_of_water

**Comment by igorbash** [comment]
I am closing this as it was already moved to the FItnesspeaker's repo
