### ISSUE TITLE
Look for DB Technology for the parking project and write about it in the wiki 

### ISSUE THREAD

**Issue by igorbash** [TechnionYP5779/team5#201]
https://github.com/TechnionYP5779/team5/wiki/DB-for-the-Parking-Project

**Comment by igorbash** [comment]
Wrote about MySql DB in wiki page

**Comment by LiorBenYamin** [comment]
Wrote about PostgreSQL DB in the wiki page

**Comment by igorbash** [comment]
Decided to use firebase
