### ISSUE TITLE
read about OAuth2 and search for implementation of this

### ISSUE THREAD

**Issue by shalev-kuba** [TechnionYP5779/team5#204]
We might create an cross platform app,
For that purpose we will have to build external server (with its own DB) and link Alexa/Google Home
to it (by getting access token - OAuth2).
By that, users can log their eating/sport activities by talking to both Alex & Google Home.

It may take a while, so it will not be ready for the demo, but it might be somthing we want to do.

for more information about OAuth2:
http://www.bubblecode.net/en/2016/01/22/understanding-oauth2/

i found repos that implement OAuth2 Server in Java: 
https://github.com/dynamind/spring-boot-security-oauth2-minimal
https://github.com/spring-projects/spring-security-oauth/tree/master/tests/annotation

@yossigil what do you think about that idea?
@shaked-sapir please have a look in this issue

**Comment by igorbash** [comment]
I am closing this as it was already moved to the FItnesspeaker's repo
