### ISSUE TITLE
check about the option of managing a couple of projects under the same repo

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/team5#206]
check so we can decide wether to split our work into two repositories or manage both parking project and "tech-care" under the same repo

**Comment by shaked-sapir** [comment]
@yossigil Hi Yossi, this is a link to the wiki we wrote about the issue: [split-repos wikipage](https://github.com/TechnionYP5779/team5/wiki/Managing-the-projects-under-the-same-repository:-Yes%5C-No-%3F) , we summed up our search and thoughts in the "Conclusions" section and think it is better to split the projects into two repos, we'll be glad to hear your opinion.

**Comment by yossigil** [comment]
Go ahead. Self-organizing team, we said
