### ISSUE TITLE
Define inner conversion between amount of grams , in relation to #207

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/team5#208]
In relation to #207 , this should include (but is not limited to) the following convertions:

- [ ] gr ---> mg

- [ ] gr ---> kg

- [ ] mg ---> gr

- [ ] mg ---> kg

- [ ] kg ---> gr

- [ ] kg ---> mg

**Comment by igorbash** [comment]
I am closing this as it was already moved to the FItnesspeaker's repo
