### ISSUE TITLE
Define convertions between different weight units, in relation to #207

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/team5#210]
According to https://www.unitconverters.net/weight-and-mass/pounds-to-ounces.htm
In relation to #207 , this should include (but is not limited to) the following convertions:

- [ ] gr ---> pounds

- [ ] gr ---> ounces

- [ ] mg ---> pounds

- [ ] mg ---> ounces

- [ ] kg ---> pounds

- [ ] kg ---> ounces 

- [ ] pounds ---> mg

- [ ] pounds ---> gr

- [ ] pounds---> kg

- [ ] ounces---> mg

- [ ] ounces---> gr

- [ ] ounces---> kg

**Comment by igorbash** [comment]
I am closing this as it was already moved to the FItnesspeaker's repo
