### ISSUE TITLE
Define conversions between different volume units, in relation to #207

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/team5#211]
According to https://www.unitconverters.net/weight-and-mass/pounds-to-ounces.htm
In relation to #207 , this should include (but is not limited to) the following convertions:

- [ ] ml ---> gallons

- [ ] ml ---> cups

- [ ] ml ---> pints

- [ ] litre ---> gallons

- [ ] litre ---> cups

- [ ] litre ---> pints

- [ ] gallons---> pints

- [ ] gallons---> ml

- [ ] gallons---> litre

- [ ] gallons---> cups

- [ ] cups---> ml

- [ ] cups---> litre

- [ ] cups---> gallons

- [ ] cups---> pints

- [ ] pints---> ml

- [ ] pints---> litre

- [ ] pints---> cups

- [ ] pints---> gallons

**Comment by igorbash** [comment]
I am closing this as it was already moved to the FItnesspeaker's repo
