### ISSUE TITLE
Move all non-general-purpose code to il.org.spartan.etc

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team5#40]

**Comment by yossigil** [comment]
vague questions get vague answers

**Comment by NirChachmovitz** [comment]
Moved the following classes:

- cCamelCase.java
- de.java
- nulling.java
- once.java
- safe.java
- Selfie.java
- zero.java

**Comment by yossigil** [comment]
these are general purpose, they can be used for fluent programming
