### ISSUE TITLE
Unit tests for enum string

### ISSUE THREAD

**Issue by shalev-kuba** [TechnionYP5779/team5#63]
as part of issue [#39]

**Comment by shaked-sapir** [comment]
reopened as part of issue #124, @shalev-kuba asking you to close

**Comment by shalev-kuba** [comment]
was closed with [this](https://github.com/TechnionYP5779/team5/commit/613b5bc73c257ec01fa781978041a7a8ddf6509c) commit

lgtm, i was impressed by your work
