### ISSUE TITLE
Define class range using tdd

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team5#79]
class range represents a range of integers, which could be infinite.

- [x] erase everhing in the class, and commit your erases.
use tdd to develop the class, as follows:
do at least one comit for each checkbox.

- [x] rang.from(2) create the infinite range 2.... 
- [x] range.from(2).from() returns the  starting point of the range
 - [x] range.from(2).to(6) returns the range 2,3,4,5
 - [x] range.to(2) returns the infinite range ..., -3, -2,-1,0,1
- [x] range.to(2).from() should return a null pointer
- [x] range.to(2).from(-5) is the range -5, -4, ...,0,1
- [x] range.numbers return an iterator over all integers in the range. 
- [x] range.to(10).interset(range.from(3)) crate the intersection range
- [x] range.from(x).to(y).includes(z) specifiy by yourself.

**Comment by shalev-kuba** [comment]
@dormaayan hey, what message should i commit with every time i finish a checkbox?

**Comment by dormaayan** [comment]
@shalev-kuba Simply briefly describe what you did in that commit and reference the issue number using `#`

**Comment by shalev-kuba** [comment]
@dormaayan got it, thanks

**Comment by shalev-kuba** [comment]
@dormaayan hey, in sections  "range.to(2) returns the infinite range ..., -3, -2,-1,0,1" and "range.from(2).to(6) returns the range 2,3,4,5" we demand method "to" to be static from one hand, and non-static from the second. can i get a hint how should i solve this problem? (since static and non static method can't have the same name in the same class)

**Comment by yossigil** [comment]
try a class Range (capitalized) to represent the type, and an enum (with zero values; only static methods) or interface range (lower case) to be the factory class for fluent programming

**Comment by shalev-kuba** [comment]
reopened as part of issue #124

**Comment by shaked-sapir** [comment]
closing it as part of #124 , nice pal 👍
