### ISSUE TITLE
use tdd to develop a fluent api that represents an arithemtical progression over BigInteger

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team5#80]
See #79 on how to define the fluent API.
Add checkboxes as necessary, note that default first value is zero, default step should e zero, and default count is infinity

**Comment by orfeld415** [comment]
- [ ]  bigRange.withDiff(1) returns range  0,1,2....

- [ ]  bigRange.from(2).withDifff(2) returns range 2,4,6....

- [ ]  bigRange.from(2).to(6).withDifff(2) return range 2,4,6

- [ ]  bigRangefrom(2).to(6).withDifff(1).Sum() returns  20

- [ ]  bigRange.to(-5).withDiff(1) return null 

- [ ]  bigRange.naturals() is the same as bigRangeWithDiff(1)

**Comment by igorbash** [comment]
Everything is fine
