### ISSUE TITLE
Refactor use of assertions

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team5#81]
All code in the project must use the azzert library in the project.

**Comment by yossigil** [comment]
Please do a search for all places that usesclass Assert of junit

**Comment by shalev-kuba** [comment]
Now you can see that the only usage of junit.Assert in our project is in azzert.
![image](https://user-images.githubusercontent.com/34859568/48714370-458de780-ec1b-11e8-9325-65968c41d7ee.png)
