### ISSUE TITLE
Use tdd to develop representing recangles in the plane defined by two corner points

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team5#82]
see #79 , #80

**Comment by igorbash** [comment]
@yossigil I did not understand, what am i supposed to do?

**Comment by yossigil** [comment]
please read documentation on commit comments in github.  we need a reference to the commit that closes an issue

**Comment by yossigil** [comment]
use il.org.spartan or etc

**Comment by yossigil** [comment]
again, incomplete issue

**Comment by igorbash** [comment]
@yossigil Why is it incomplete?

**Comment by igorbash** [comment]
reopened as part of issue #124, @orfeld415 asking you to close

**Comment by orfeld415** [comment]
lgtm
