### ISSUE TITLE
Refactor use of assertions Of enum CSV,class idiomatic, class box, class Bool

### ISSUE THREAD

**Issue by shalev-kuba** [TechnionYP5779/team5#85]
as part of issue [#81]

**Comment by shalev-kuba** [comment]
took 1/2 hour

**Comment by yossigil** [comment]
please include a reference to the commit that closed this

**Comment by shalev-kuba** [comment]
@yossigil hey, i added commit that referenced this issue before, what is wrong with that?

**Comment by yossigil** [comment]
this did not do it, as you notice. please do a little web research on the topic

**Comment by shalev-kuba** [comment]
@yossigil there is a link to the related commit:
https://github.com/TechnionYP5779/team5/commit/f7e3ad9922e8ff4f75e8e7d2de66a2008b757a6f

as you can see, it switches all usage of assertion by using azzert as required in issue #81 (which this issue is part of it)

**Comment by yossigil** [comment]
i guess I am not getting through. this is not a grade I give... I just ask that next time you close issues with an appropriate message in the commit. OK?

**Comment by shalev-kuba** [comment]
@yossigil got it,here is how i see the commit's message (i upload an image)
![image](https://user-images.githubusercontent.com/34859568/48223761-9c382d80-e3a0-11e8-920f-65c14b8c81d1.png)
is this a properly message? just to know for the next time..
