### ISSUE TITLE
Use TDD to develop a function iterables.alternate that takes two iterables, and returns an iterable that returns elements in these in alternating order, until the shortest

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team5#94]
_From @yossigil on November 8, 2018 10:18_

Use TDD to develop a function iterables.alternate that takes two iterables over elements of the same kind, and returns an iterable that returns elements in these in alternating order, until the shortest one is exhausted, and then continues with the other.

use TDD to design and implement specification for the case that one or both arguments are null.
be sure to break tests before you write any line of code.

_Copied from original issue: TechnionYP5779/team6#60_

**Comment by yossigil** [comment]
This issue was copied to TechnionYP5779/team1#55

**Comment by yossigil** [comment]
This issue was copied to TechnionYP5779/team2#52

**Comment by yossigil** [comment]
This issue was copied to TechnionYP5779/team3#69

**Comment by yossigil** [comment]
This issue was copied to TechnionYP5779/team4#89

**Comment by LiorBenYamin** [comment]
Hi Nir,
lgtm, the tests and the function looks great
