### ISSUE TITLE
use TDD to define class angle

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team5#96]
_From @yossigil on November 8, 2018 11:1_

that represents an angle on the plane; angles can be added, negated and substracted
here are some hints.

- [x] angle.degrees(20) creates an angle of 20 degrees
- [x] angle.radians(1) creates an angle of 1 radian
- [x] angle.pi is an angle of pi radians
- [x] angle.halfPi is an engle of half Pi radians
- [x] angle.halfPi.add(angle.degrees(20)) is an engle of half Pi radians + 20 radians
- [x] angle.halfPi.add((20)) is an engle of half Pi radians + 20 degrees
- [x] angle.pi.degrees() is 180
- [x] angle.of(20).degrees() is 180
- [x] angle.pi.radians() is PI/2

be sure to create code that try to cheat the tests, e.g. 
`class angle { static angle degrees(double x) { return new angle(20); }`

_Copied from original issue: TechnionYP5779/team6#62_

**Comment by LiorBenYamin** [comment]
in checkbox 5, why the answer should be half pi radians + 20 radians, and not half pi radians + 20 degrees? it does not make any sense.

**Comment by LiorBenYamin** [comment]
> in checkbox 5, why the answer should be half pi radians + 20 radians, and not half pi radians + 20 degrees? it does not make any sense.

?

**Comment by LiorBenYamin** [comment]
> in checkbox 5, why the answer should be half pi radians + 20 radians, and not half pi radians + 20 degrees? it does not make any sense.

Decided that checkbox 5 is a typo

**Comment by yossigil** [comment]
typo

**Comment by yossigil** [comment]
data members can be public, but only if immutable:

public double degrees;
public double radians;	public double radians;

**Comment by LiorBenYamin** [comment]
@NirChachmovitz  please check that I did this issue correctly

**Comment by NirChachmovitz** [comment]
Hi Lior,
Looks great and it seems like you have invested a serious amount of time working on it.
Good night
